export interface City {
  name: string;
  nameHindi: string;
  state: string;
  stateHindi: string;
  latitude: number;
  longitude: number;
}

export const indianCities: City[] = [
  // Maharashtra
  { name: "Mumbai", nameHindi: "मुंबई", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.0760, longitude: 72.8777 },
  { name: "Pune", nameHindi: "पुणे", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 18.5204, longitude: 73.8567 },
  { name: "Nagpur", nameHindi: "नागपुर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 21.1458, longitude: 79.0882 },
  { name: "Thane", nameHindi: "ठाणे", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.2183, longitude: 72.9781 },
  { name: "Nashik", nameHindi: "नाशिक", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.9975, longitude: 73.7898 },
  { name: "Kalyan", nameHindi: "कल्याण", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.2437, longitude: 73.1355 },
  { name: "Vasai", nameHindi: "वसई", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.4036, longitude: 72.8264 },
  { name: "Aurangabad", nameHindi: "औरंगाबाद", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.8762, longitude: 75.3433 },
  { name: "Navi Mumbai", nameHindi: "नवी मुंबई", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.0330, longitude: 73.0297 },
  { name: "Solapur", nameHindi: "सोलापुर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 17.6599, longitude: 75.9064 },
  { name: "Mira-Bhayandar", nameHindi: "मीरा-भायंदर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.2952, longitude: 72.8543 },
  { name: "Bhiwandi", nameHindi: "भिवंडी", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.3002, longitude: 73.0636 },
  { name: "Amravati", nameHindi: "अमरावती", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 20.9374, longitude: 77.7796 },
  { name: "Nanded", nameHindi: "नांदेड़", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.1383, longitude: 77.3210 },
  { name: "Kolhapur", nameHindi: "कोल्हापुर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 16.7050, longitude: 74.2433 },
  { name: "Akola", nameHindi: "अकोला", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 20.7002, longitude: 77.0082 },
  { name: "Latur", nameHindi: "लातूर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 18.4088, longitude: 76.5604 },
  { name: "Dhule", nameHindi: "धुळे", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 20.9042, longitude: 74.7749 },
  { name: "Ahmednagar", nameHindi: "अहमदनगर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.0948, longitude: 74.7480 },
  { name: "Chandrapur", nameHindi: "चंद्रपुर", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.9615, longitude: 79.2961 },
  { name: "Parbhani", nameHindi: "परभणी", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.2704, longitude: 76.7749 },
  { name: "Jalgaon", nameHindi: "जळगांव", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 21.0077, longitude: 75.5626 },
  { name: "Bhusawal", nameHindi: "भुसावळ", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 21.0441, longitude: 75.7849 },
  { name: "Panvel", nameHindi: "पनवेल", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 18.9894, longitude: 73.1178 },
  { name: "Satara", nameHindi: "सातारा", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 17.6805, longitude: 74.0183 },
  { name: "Beed", nameHindi: "बीड", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 18.9888, longitude: 76.1563 },
  { name: "Yavatmal", nameHindi: "यवतमाळ", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 20.3897, longitude: 78.1227 },
  { name: "Wardha", nameHindi: "वर्धा", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 20.7453, longitude: 78.6022 },
  { name: "Hingoli", nameHindi: "हिंगोली", state: "Maharashtra", stateHindi: "महाराष्ट्र", latitude: 19.7148, longitude: 77.1547 },

  // Delhi
  { name: "Delhi", nameHindi: "दिल्ली", state: "Delhi", stateHindi: "दिल्ली", latitude: 28.7041, longitude: 77.1025 },
  { name: "New Delhi", nameHindi: "नई दिल्ली", state: "Delhi", stateHindi: "दिल्ली", latitude: 28.6139, longitude: 77.2090 },
  { name: "Dwarka", nameHindi: "द्वारका", state: "Delhi", stateHindi: "दिल्ली", latitude: 28.5921, longitude: 77.0460 },
  { name: "Rohini", nameHindi: "रोहिणी", state: "Delhi", stateHindi: "दिल्ली", latitude: 28.7041, longitude: 77.1025 },
  { name: "Janakpuri", nameHindi: "जनकपुरी", state: "Delhi", stateHindi: "दिल्ली", latitude: 28.6219, longitude: 77.0834 },

  // Uttar Pradesh
  { name: "Lucknow", nameHindi: "लखनऊ", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.8467, longitude: 80.9462 },
  { name: "Kanpur", nameHindi: "कानपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.4499, longitude: 80.3319 },
  { name: "Ghaziabad", nameHindi: "गाजियाबाद", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.6692, longitude: 77.4538 },
  { name: "Agra", nameHindi: "आगरा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.1767, longitude: 78.0081 },
  { name: "Varanasi", nameHindi: "वाराणसी", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.3176, longitude: 82.9739 },
  { name: "Meerut", nameHindi: "मेरठ", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.9845, longitude: 77.7064 },
  { name: "Allahabad", nameHindi: "इलाहाबाद", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.4358, longitude: 81.8463 },
  { name: "Bareilly", nameHindi: "बरेली", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.3670, longitude: 79.4304 },
  { name: "Aligarh", nameHindi: "अलीगढ़", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.8974, longitude: 78.0880 },
  { name: "Moradabad", nameHindi: "मुरादाबाद", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.8386, longitude: 78.7733 },
  { name: "Saharanpur", nameHindi: "सहारनपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 29.9680, longitude: 77.5552 },
  { name: "Gorakhpur", nameHindi: "गोरखपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.7606, longitude: 83.3732 },
  { name: "Noida", nameHindi: "नोएडा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.5355, longitude: 77.3910 },
  { name: "Firozabad", nameHindi: "फिरोजाबाद", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.1592, longitude: 78.3957 },
  { name: "Jhansi", nameHindi: "झांसी", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.4484, longitude: 78.5685 },
  { name: "Muzaffarnagar", nameHindi: "मुजफ्फरनगर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 29.4726, longitude: 77.7085 },
  { name: "Mathura", nameHindi: "मथुरा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.4924, longitude: 77.6737 },
  { name: "Rampur", nameHindi: "रामपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.8055, longitude: 79.0266 },
  { name: "Shahjahanpur", nameHindi: "शाहजहांपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.8815, longitude: 79.9864 },
  { name: "Farrukhabad", nameHindi: "फर्रुखाबाद", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.3895, longitude: 79.5734 },
  { name: "Hapur", nameHindi: "हापुड़", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.7306, longitude: 77.7776 },
  { name: "Etawah", nameHindi: "इटावा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.7750, longitude: 79.0298 },
  { name: "Mirzapur", nameHindi: "मिर्जापुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.1460, longitude: 82.5690 },
  { name: "Bulandshahr", nameHindi: "बुलंदशहर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.4068, longitude: 77.8498 },
  { name: "Sambhal", nameHindi: "संभल", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.5843, longitude: 78.5527 },
  { name: "Amroha", nameHindi: "अमरोहा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.9034, longitude: 78.4684 },
  { name: "Hardoi", nameHindi: "हरदोई", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.4074, longitude: 80.1311 },
  { name: "Fatehpur", nameHindi: "फतेहपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.9289, longitude: 80.8103 },
  { name: "Raebareli", nameHindi: "रायबरेली", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.2124, longitude: 81.2393 },
  { name: "Orai", nameHindi: "उरई", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.9897, longitude: 79.4503 },
  { name: "Sitapur", nameHindi: "सीतापुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.5677, longitude: 80.6780 },
  { name: "Bahraich", nameHindi: "बहराइच", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.5743, longitude: 81.5946 },
  { name: "Modinagar", nameHindi: "मोदीनगर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.9231, longitude: 77.6178 },
  { name: "Unnao", nameHindi: "उन्नाव", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.5465, longitude: 80.4879 },
  { name: "Jaunpur", nameHindi: "जौनपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.7648, longitude: 82.6892 },
  { name: "Lakhimpur", nameHindi: "लखीमपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.9479, longitude: 80.7780 },
  { name: "Hathras", nameHindi: "हाथरस", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.5927, longitude: 78.0502 },
  { name: "Banda", nameHindi: "बांदा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.4765, longitude: 80.3348 },
  { name: "Pilibhit", nameHindi: "पीलीभीत", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.6339, longitude: 79.8047 },
  { name: "Barabanki", nameHindi: "बाराबंकी", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.9241, longitude: 81.1945 },
  { name: "Khurja", nameHindi: "खुर्जा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 28.2505, longitude: 77.8564 },
  { name: "Gonda", nameHindi: "गोंडा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.1334, longitude: 81.9614 },
  { name: "Mainpuri", nameHindi: "मैनपुरी", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.2380, longitude: 79.0317 },
  { name: "Lalitpur", nameHindi: "ललितपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 24.6901, longitude: 78.4285 },
  { name: "Etah", nameHindi: "एटा", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 27.6312, longitude: 78.6574 },
  { name: "Deoria", nameHindi: "देवरिया", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.5024, longitude: 83.7791 },
  { name: "Azamgarh", nameHindi: "आजमगढ़", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.0685, longitude: 83.1840 },
  { name: "Sultanpur", nameHindi: "सुल्तानपुर", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 26.2645, longitude: 82.0764 },
  { name: "Pratapgarh", nameHindi: "प्रतापगढ़", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.8918, longitude: 81.9378 },
  { name: "Mau", nameHindi: "मऊ", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.9417, longitude: 83.5611 },
  { name: "Ballia", nameHindi: "बलिया", state: "Uttar Pradesh", stateHindi: "उत्तर प्रदेश", latitude: 25.7522, longitude: 84.1491 },

  // Gujarat
  { name: "Ahmedabad", nameHindi: "अहमदाबाद", state: "Gujarat", stateHindi: "गुजरात", latitude: 23.0225, longitude: 72.5714 },
  { name: "Surat", nameHindi: "सूरत", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.1702, longitude: 72.8311 },
  { name: "Vadodara", nameHindi: "वडोदरा", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.3072, longitude: 73.1812 },
  { name: "Rajkot", nameHindi: "राजकोट", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.3039, longitude: 70.8022 },
  { name: "Bhavnagar", nameHindi: "भावनगर", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.7645, longitude: 72.1519 },
  { name: "Jamnagar", nameHindi: "जामनगर", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.4707, longitude: 70.0577 },
  { name: "Junagadh", nameHindi: "जूनागढ़", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.5222, longitude: 70.4579 },
  { name: "Gandhinagar", nameHindi: "गांधीनगर", state: "Gujarat", stateHindi: "गुजरात", latitude: 23.2156, longitude: 72.6369 },
  { name: "Anand", nameHindi: "आनंद", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.5645, longitude: 72.9289 },
  { name: "Navsari", nameHindi: "नवसारी", state: "Gujarat", stateHindi: "गुजरात", latitude: 20.9463, longitude: 72.9270 },
  { name: "Morbi", nameHindi: "मोरबी", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.8196, longitude: 70.8374 },
  { name: "Nadiad", nameHindi: "नडियाद", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.6939, longitude: 72.8614 },
  { name: "Bharuch", nameHindi: "भरूच", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.7051, longitude: 72.9959 },
  { name: "Vapi", nameHindi: "वापी", state: "Gujarat", stateHindi: "गुजरात", latitude: 20.3712, longitude: 72.9051 },
  { name: "Veraval", nameHindi: "वेरावल", state: "Gujarat", stateHindi: "गुजरात", latitude: 20.9077, longitude: 70.3660 },
  { name: "Porbandar", nameHindi: "पोरबंदर", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.6417, longitude: 69.6293 },
  { name: "Godhra", nameHindi: "गोधरा", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.7756, longitude: 73.6135 },
  { name: "Botad", nameHindi: "बोटाद", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.1693, longitude: 71.6667 },
  { name: "Amreli", nameHindi: "अमरेली", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.6005, longitude: 71.2181 },
  { name: "Surendranagar", nameHindi: "सुरेंद्रनगर", state: "Gujarat", stateHindi: "गुजरात", latitude: 22.7196, longitude: 71.6369 },
  { name: "Bhuj", nameHindi: "भुज", state: "Gujarat", stateHindi: "गुजरात", latitude: 23.2420, longitude: 69.6669 },
  { name: "Patan", nameHindi: "पाटन", state: "Gujarat", stateHindi: "गुजरात", latitude: 23.8502, longitude: 72.1342 },
  { name: "Palanpur", nameHindi: "पालनपुर", state: "Gujarat", stateHindi: "गुजरात", latitude: 24.1717, longitude: 72.4281 },
  { name: "Valsad", nameHindi: "वलसाड", state: "Gujarat", stateHindi: "गुजरात", latitude: 20.5992, longitude: 72.9342 },
  { name: "Mahesana", nameHindi: "महेसाणा", state: "Gujarat", stateHindi: "गुजरात", latitude: 23.5880, longitude: 72.3693 },
  { name: "Jetpur", nameHindi: "जेतपुर", state: "Gujarat", stateHindi: "गुजरात", latitude: 21.7549, longitude: 70.6235 },

  // Rajasthan
  { name: "Jaipur", nameHindi: "जयपुर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.9124, longitude: 75.7873 },
  { name: "Jodhpur", nameHindi: "जोधपुर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.2389, longitude: 73.0243 },
  { name: "Kota", nameHindi: "कोटा", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 25.2138, longitude: 75.8648 },
  { name: "Bikaner", nameHindi: "बीकानेर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 28.0229, longitude: 73.3119 },
  { name: "Udaipur", nameHindi: "उदयपुर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 24.5854, longitude: 73.7125 },
  { name: "Ajmer", nameHindi: "अजमेर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.4499, longitude: 74.6399 },
  { name: "Bhilwara", nameHindi: "भीलवाड़ा", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 25.3407, longitude: 74.6269 },
  { name: "Alwar", nameHindi: "अलवर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 27.5530, longitude: 76.6346 },
  { name: "Bharatpur", nameHindi: "भरतपुर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 27.2152, longitude: 77.4910 },
  { name: "Sikar", nameHindi: "सीकर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 27.6094, longitude: 75.1399 },
  { name: "Pali", nameHindi: "पाली", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 25.7781, longitude: 73.3232 },
  { name: "Sri Ganganagar", nameHindi: "श्री गंगानगर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 29.9157, longitude: 73.8772 },
  { name: "Kishangarh", nameHindi: "किशनगढ़", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.5821, longitude: 74.8648 },
  { name: "Baran", nameHindi: "बारां", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 25.1009, longitude: 76.5132 },
  { name: "Dhaulpur", nameHindi: "धौलपुर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.6947, longitude: 77.8828 },
  { name: "Tonk", nameHindi: "टोंक", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.1615, longitude: 75.7849 },
  { name: "Beawar", nameHindi: "ब्यावर", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 26.1020, longitude: 74.3200 },
  { name: "Hanumangarh", nameHindi: "हनुमानगढ़", state: "Rajasthan", stateHindi: "राजस्थान", latitude: 29.5817, longitude: 74.3084 },

  // Karnataka
  { name: "Bangalore", nameHindi: "बेंगलुरु", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 12.9716, longitude: 77.5946 },
  { name: "Mysore", nameHindi: "मैसूर", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 12.2958, longitude: 76.6394 },
  { name: "Hubli", nameHindi: "हुबली", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 15.3647, longitude: 75.1240 },
  { name: "Mangalore", nameHindi: "मंगलौर", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 12.9141, longitude: 74.8560 },
  { name: "Belgaum", nameHindi: "बेलगाम", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 15.8497, longitude: 74.4977 },
  { name: "Gulbarga", nameHindi: "गुलबर्गा", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 17.3297, longitude: 76.8343 },
  { name: "Davanagere", nameHindi: "दावणगेरे", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 14.4644, longitude: 75.9217 },
  { name: "Bellary", nameHindi: "बेल्लारी", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 15.1394, longitude: 76.9214 },
  { name: "Bijapur", nameHindi: "बीजापुर", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 16.8302, longitude: 75.7100 },
  { name: "Shimoga", nameHindi: "शिमोगा", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 13.9299, longitude: 75.5681 },
  { name: "Tumkur", nameHindi: "तुमकुर", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 13.3379, longitude: 77.1022 },
  { name: "Raichur", nameHindi: "राइचूर", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 16.2071, longitude: 77.3439 },
  { name: "Bidar", nameHindi: "बीदर", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 17.9104, longitude: 77.5200 },
  { name: "Hospet", nameHindi: "होस्पेट", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 15.2693, longitude: 76.3869 },
  { name: "Hassan", nameHindi: "हासन", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 13.0072, longitude: 76.0962 },
  { name: "Bhadravati", nameHindi: "भद्रावती", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 13.8509, longitude: 75.7108 },
  { name: "Chitradurga", nameHindi: "चित्रदुर्गा", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 14.2251, longitude: 76.3958 },
  { name: "Udupi", nameHindi: "उडुपी", state: "Karnataka", stateHindi: "कर्नाटक", latitude: 13.3409, longitude: 74.7421 },

  // West Bengal
  { name: "Kolkata", nameHindi: "कोलकाता", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 22.5726, longitude: 88.3639 },
  { name: "Howrah", nameHindi: "हावड़ा", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 22.5958, longitude: 88.2636 },
  { name: "Durgapur", nameHindi: "दुर्गापुर", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 23.4209, longitude: 87.3119 },
  { name: "Asansol", nameHindi: "आसनसोल", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 23.6739, longitude: 86.9524 },
  { name: "Siliguri", nameHindi: "सिलीगुड़ी", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 26.7271, longitude: 88.3953 },
  { name: "Malda", nameHindi: "मालदा", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 25.0961, longitude: 88.1435 },
  { name: "Baharampur", nameHindi: "बहरामपुर", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 24.1170, longitude: 88.2515 },
  { name: "Habra", nameHindi: "हबरा", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 22.8335, longitude: 88.6324 },
  { name: "Kharagpur", nameHindi: "खड़गपुर", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 22.3460, longitude: 87.2319 },
  { name: "Jalpaiguri", nameHindi: "जलपाईगुड़ी", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 26.5167, longitude: 88.7167 },
  { name: "Krishnanagar", nameHindi: "कृष्णनगर", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 23.4058, longitude: 88.5019 },
  { name: "Raniganj", nameHindi: "रानीगंज", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 23.6166, longitude: 87.1281 },
  { name: "Haldia", nameHindi: "हल्दिया", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 22.0667, longitude: 88.0667 },
  { name: "Raiganj", nameHindi: "राय गंज", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 25.6218, longitude: 88.1227 },
  { name: "Midnapore", nameHindi: "मिदनापुर", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 22.4186, longitude: 87.3267 },
  { name: "Cooch Behar", nameHindi: "कूच बिहार", state: "West Bengal", stateHindi: "पश्चिम बंगाल", latitude: 26.3269, longitude: 89.4489 },

  // Tamil Nadu
  { name: "Chennai", nameHindi: "चेन्नई", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 13.0827, longitude: 80.2707 },
  { name: "Coimbatore", nameHindi: "कोयम्बटूर", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 11.0168, longitude: 76.9558 },
  { name: "Madurai", nameHindi: "मदुराई", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 9.9252, longitude: 78.1198 },
  { name: "Tiruchirappalli", nameHindi: "तिरुचिरापल्ली", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 10.7905, longitude: 78.7047 },
  { name: "Salem", nameHindi: "सेलम", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 11.6643, longitude: 78.1460 },
  { name: "Tirunelveli", nameHindi: "तिरुनेलवेली", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 8.7139, longitude: 77.7567 },
  { name: "Tiruppur", nameHindi: "तिरुप्पुर", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 11.1085, longitude: 77.3411 },
  { name: "Erode", nameHindi: "इरोड", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 11.3410, longitude: 77.7172 },
  { name: "Vellore", nameHindi: "वेल्लोर", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 12.9165, longitude: 79.1325 },
  { name: "Thoothukudi", nameHindi: "तूतुकुडी", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 8.7642, longitude: 78.1348 },
  { name: "Dindigul", nameHindi: "दिंडीगुल", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 10.3673, longitude: 77.9803 },
  { name: "Thanjavur", nameHindi: "तंजावुर", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 10.7870, longitude: 79.1378 },
  { name: "Ranipet", nameHindi: "रानीपेट", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 12.9342, longitude: 79.3370 },
  { name: "Sivakasi", nameHindi: "शिवकाशी", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 9.4530, longitude: 77.7910 },
  { name: "Karur", nameHindi: "करूर", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 10.9601, longitude: 78.0766 },
  { name: "Rajapalayam", nameHindi: "राजापालयम", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 9.4481, longitude: 77.5550 },
  { name: "Pudukkottai", nameHindi: "पुदुक्कोट्टै", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 10.3883, longitude: 78.8242 },
  { name: "Pollachi", nameHindi: "पोल्लाची", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 10.6581, longitude: 77.0080 },
  { name: "Ramanathapuram", nameHindi: "रामनाथपुरम", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 9.3648, longitude: 78.8370 },
  { name: "Ambur", nameHindi: "अंबुर", state: "Tamil Nadu", stateHindi: "तमिलनाडु", latitude: 12.7916, longitude: 78.7167 },

  // Telangana
  { name: "Hyderabad", nameHindi: "हैदराबाद", state: "Telangana", stateHindi: "तेलंगाना", latitude: 17.3850, longitude: 78.4867 },
  { name: "Warangal", nameHindi: "वारंगल", state: "Telangana", stateHindi: "तेलंगाना", latitude: 17.9689, longitude: 79.5941 },
  { name: "Nizamabad", nameHindi: "निजामाबाद", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.6725, longitude: 78.0941 },
  { name: "Khammam", nameHindi: "खम्मम", state: "Telangana", stateHindi: "तेलंगाना", latitude: 17.2473, longitude: 80.1514 },
  { name: "Karimnagar", nameHindi: "करीमनगर", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.4386, longitude: 79.1288 },
  { name: "Ramagundam", nameHindi: "रामागुंडम", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.4455, longitude: 79.4919 },
  { name: "Mahabubnagar", nameHindi: "महबूबनगर", state: "Telangana", stateHindi: "तेलंगाना", latitude: 16.7462, longitude: 77.9982 },
  { name: "Nalgonda", nameHindi: "नलगोंडा", state: "Telangana", stateHindi: "तेलंगाना", latitude: 17.0568, longitude: 79.2687 },
  { name: "Adilabad", nameHindi: "आदिलाबाद", state: "Telangana", stateHindi: "तेलंगाना", latitude: 19.6669, longitude: 78.5305 },
  { name: "Suryapet", nameHindi: "सूर्यापेट", state: "Telangana", stateHindi: "तेलंगाना", latitude: 17.1500, longitude: 79.6167 },
  { name: "Miryalaguda", nameHindi: "मिर्यालगुडा", state: "Telangana", stateHindi: "तेलंगाना", latitude: 16.8667, longitude: 79.5667 },
  { name: "Jagtial", nameHindi: "जगतियाल", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.7904, longitude: 78.9176 },
  { name: "Mancherial", nameHindi: "मंचेरियल", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.8715, longitude: 79.4592 },
  { name: "Kamareddy", nameHindi: "कामारेड्डी", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.3218, longitude: 78.3424 },
  { name: "Medak", nameHindi: "मेडक", state: "Telangana", stateHindi: "तेलंगाना", latitude: 18.0488, longitude: 78.2747 },

  // Andhra Pradesh
  { name: "Visakhapatnam", nameHindi: "विशाखापत्तनम", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 17.6868, longitude: 83.2185 },
  { name: "Vijayawada", nameHindi: "विजयवाड़ा", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 16.5062, longitude: 80.6480 },
  { name: "Guntur", nameHindi: "गुंटूर", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 16.3067, longitude: 80.4365 },
  { name: "Nellore", nameHindi: "नेल्लूर", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 14.4426, longitude: 79.9865 },
  { name: "Kurnool", nameHindi: "कुर्नूल", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 15.8281, longitude: 78.0373 },
  { name: "Rajahmundry", nameHindi: "राजामुंद्री", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 17.0005, longitude: 81.8040 },
  { name: "Tirupati", nameHindi: "तिरुपति", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 13.6288, longitude: 79.4192 },
  { name: "Anantapur", nameHindi: "अनंतपुर", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 14.6819, longitude: 77.6006 },
  { name: "Chittoor", nameHindi: "चित्तूर", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 13.2172, longitude: 79.1003 },
  { name: "Ongole", nameHindi: "ओंगोल", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 15.5057, longitude: 80.0499 },
  { name: "Eluru", nameHindi: "एलुरु", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 16.7107, longitude: 81.0952 },
  { name: "Kadapa", nameHindi: "कडपा", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 14.4673, longitude: 78.8242 },
  { name: "Machilipatnam", nameHindi: "मछलीपत्तनम", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 16.1874, longitude: 81.1386 },
  { name: "Adoni", nameHindi: "अदोनी", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 15.6267, longitude: 77.2750 },
  { name: "Tenali", nameHindi: "तेनाली", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 16.2430, longitude: 80.6465 },
  { name: "Proddatur", nameHindi: "प्रोद्दातुर", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 14.7504, longitude: 78.5482 },
  { name: "Hindupur", nameHindi: "हिंदुपुर", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 13.8283, longitude: 77.4917 },
  { name: "Bhimavaram", nameHindi: "भीमावरम", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 16.5449, longitude: 81.5212 },
  { name: "Madanapalle", nameHindi: "मदनपल्ले", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 13.5503, longitude: 78.5023 },
  { name: "Guntakal", nameHindi: "गुंतकल", state: "Andhra Pradesh", stateHindi: "आंध्र प्रदेश", latitude: 15.1669, longitude: 77.3811 },

  // Madhya Pradesh
  { name: "Bhopal", nameHindi: "भोपाल", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.2599, longitude: 77.4126 },
  { name: "Indore", nameHindi: "इंदौर", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 22.7196, longitude: 75.8577 },
  { name: "Jabalpur", nameHindi: "जबलपुर", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.1815, longitude: 79.9864 },
  { name: "Gwalior", nameHindi: "ग्वालियर", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 26.2183, longitude: 78.1828 },
  { name: "Ujjain", nameHindi: "उज्जैन", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.1793, longitude: 75.7849 },
  { name: "Sagar", nameHindi: "सागर", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.8388, longitude: 78.7378 },
  { name: "Dewas", nameHindi: "देवास", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 22.9676, longitude: 76.0534 },
  { name: "Satna", nameHindi: "सतना", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 24.5671, longitude: 80.8341 },
  { name: "Ratlam", nameHindi: "रतलाम", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.3315, longitude: 75.0367 },
  { name: "Rewa", nameHindi: "रीवा", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 24.5370, longitude: 81.2958 },
  { name: "Murwara", nameHindi: "मुरवारा", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.8371, longitude: 80.3931 },
  { name: "Singrauli", nameHindi: "सिंगरौली", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 24.1997, longitude: 82.6739 },
  { name: "Burhanpur", nameHindi: "बुरहानपुर", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 21.3009, longitude: 76.2291 },
  { name: "Khandwa", nameHindi: "खंडवा", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 21.8245, longitude: 76.3502 },
  { name: "Morena", nameHindi: "मुरैना", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 26.5026, longitude: 78.0014 },
  { name: "Bhind", nameHindi: "भिंड", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 26.5645, longitude: 78.7892 },
  { name: "Chhindwara", nameHindi: "छिंदवाड़ा", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 22.0572, longitude: 78.9389 },
  { name: "Guna", nameHindi: "गुना", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 24.6473, longitude: 77.3115 },
  { name: "Shivpuri", nameHindi: "शिवपुरी", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 25.4244, longitude: 77.6613 },
  { name: "Vidisha", nameHindi: "विदिशा", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.5251, longitude: 77.8081 },
  { name: "Damoh", nameHindi: "दमोह", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 23.8315, longitude: 79.4421 },
  { name: "Mandsaur", nameHindi: "मंदसौर", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 24.0765, longitude: 75.0714 },
  { name: "Betul", nameHindi: "बैतूल", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 21.9042, longitude: 77.8977 },
  { name: "Neemuch", nameHindi: "नीमच", state: "Madhya Pradesh", stateHindi: "मध्य प्रदेश", latitude: 24.4739, longitude: 74.8799 },

  // Bihar
  { name: "Patna", nameHindi: "पटना", state: "Bihar", stateHindi: "बिहार", latitude: 25.5941, longitude: 85.1376 },
  { name: "Gaya", nameHindi: "गया", state: "Bihar", stateHindi: "बिहार", latitude: 24.7914, longitude: 85.0002 },
  { name: "Bhagalpur", nameHindi: "भागलपुर", state: "Bihar", stateHindi: "बिहार", latitude: 25.2425, longitude: 86.9842 },
  { name: "Muzaffarpur", nameHindi: "मुजफ्फरपुर", state: "Bihar", stateHindi: "बिहार", latitude: 26.1209, longitude: 85.3647 },
  { name: "Purnia", nameHindi: "पूर्णिया", state: "Bihar", stateHindi: "बिहार", latitude: 25.7771, longitude: 87.4753 },
  { name: "Darbhanga", nameHindi: "दरभंगा", state: "Bihar", stateHindi: "बिहार", latitude: 26.1542, longitude: 85.8918 },
  { name: "Bihar Sharif", nameHindi: "बिहार शरीफ", state: "Bihar", stateHindi: "बिहार", latitude: 25.2013, longitude: 85.5155 },
  { name: "Arrah", nameHindi: "आरा", state: "Bihar", stateHindi: "बिहार", latitude: 25.5561, longitude: 84.6644 },
  { name: "Begusarai", nameHindi: "बेगूसराय", state: "Bihar", stateHindi: "बिहार", latitude: 25.4158, longitude: 86.1267 },
  { name: "Katihar", nameHindi: "कटिहार", state: "Bihar", stateHindi: "बिहार", latitude: 25.5394, longitude: 87.5761 },
  { name: "Munger", nameHindi: "मुंगेर", state: "Bihar", stateHindi: "बिहार", latitude: 25.3728, longitude: 86.4733 },
  { name: "Chhapra", nameHindi: "छपरा", state: "Bihar", stateHindi: "बिहार", latitude: 25.7830, longitude: 84.7278 },
  { name: "Sasaram", nameHindi: "सासाराम", state: "Bihar", stateHindi: "बिहार", latitude: 24.9530, longitude: 84.0113 },
  { name: "Hajipur", nameHindi: "हाजीपुर", state: "Bihar", stateHindi: "बिहार", latitude: 25.6857, longitude: 85.2079 },
  { name: "Dehri", nameHindi: "डेहरी", state: "Bihar", stateHindi: "बिहार", latitude: 24.9045, longitude: 84.1820 },
  { name: "Siwan", nameHindi: "सीवान", state: "Bihar", stateHindi: "बिहार", latitude: 26.2190, longitude: 84.3560 },
  { name: "Motihari", nameHindi: "मोतिहारी", state: "Bihar", stateHindi: "बिहार", latitude: 26.6487, longitude: 84.9194 },
  { name: "Saharsa", nameHindi: "सहरसा", state: "Bihar", stateHindi: "बिहार", latitude: 25.8746, longitude: 86.5960 },
  { name: "Buxar", nameHindi: "बक्सर", state: "Bihar", stateHindi: "बिहार", latitude: 25.5651, longitude: 83.9777 },
  { name: "Kishanganj", nameHindi: "किशनगंज", state: "Bihar", stateHindi: "बिहार", latitude: 26.1061, longitude: 87.9495 },

  // Odisha
  { name: "Bhubaneswar", nameHindi: "भुवनेश्वर", state: "Odisha", stateHindi: "ओडिशा", latitude: 20.2961, longitude: 85.8245 },
  { name: "Cuttack", nameHindi: "कटक", state: "Odisha", stateHindi: "ओडिशा", latitude: 20.4625, longitude: 85.8830 },
  { name: "Rourkela", nameHindi: "राउरकेला", state: "Odisha", stateHindi: "ओडिशा", latitude: 22.2604, longitude: 84.8536 },
  { name: "Brahmapur", nameHindi: "ब्रह्मपुर", state: "Odisha", stateHindi: "ओडिशा", latitude: 19.3149, longitude: 84.7941 },
  { name: "Sambalpur", nameHindi: "संबलपुर", state: "Odisha", stateHindi: "ओडिशा", latitude: 21.4669, longitude: 83.9812 },
  { name: "Puri", nameHindi: "पुरी", state: "Odisha", stateHindi: "ओडिशा", latitude: 19.8135, longitude: 85.8312 },
  { name: "Balasore", nameHindi: "बालासोर", state: "Odisha", stateHindi: "ओडिशा", latitude: 21.4934, longitude: 86.9336 },
  { name: "Bhadrak", nameHindi: "भद्रक", state: "Odisha", stateHindi: "ओडिशा", latitude: 21.0581, longitude: 86.5086 },
  { name: "Baripada", nameHindi: "बारीपदा", state: "Odisha", stateHindi: "ओडिशा", latitude: 21.9347, longitude: 86.7228 },
  { name: "Jharsuguda", nameHindi: "झारसुगुडा", state: "Odisha", stateHindi: "ओडिशा", latitude: 21.8558, longitude: 84.0060 },

  // Jharkhand
  { name: "Ranchi", nameHindi: "रांची", state: "Jharkhand", stateHindi: "झारखंड", latitude: 23.3441, longitude: 85.3096 },
  { name: "Jamshedpur", nameHindi: "जमशेदपुर", state: "Jharkhand", stateHindi: "झारखंड", latitude: 22.8046, longitude: 86.2029 },
  { name: "Dhanbad", nameHindi: "धनबाद", state: "Jharkhand", stateHindi: "झारखंड", latitude: 23.7957, longitude: 86.4304 },
  { name: "Bokaro", nameHindi: "बोकारो", state: "Jharkhand", stateHindi: "झारखंड", latitude: 23.6693, longitude: 86.1511 },
  { name: "Deoghar", nameHindi: "देवघर", state: "Jharkhand", stateHindi: "झारखंड", latitude: 24.4850, longitude: 86.6918 },
  { name: "Phusro", nameHindi: "फुसरो", state: "Jharkhand", stateHindi: "झारखंड", latitude: 23.6793, longitude: 86.0026 },
  { name: "Hazaribagh", nameHindi: "हजारीबाग", state: "Jharkhand", stateHindi: "झारखंड", latitude: 23.9981, longitude: 85.3644 },
  { name: "Giridih", nameHindi: "गिरिडीह", state: "Jharkhand", stateHindi: "झारखंड", latitude: 24.1854, longitude: 86.3094 },
  { name: "Ramgarh", nameHindi: "रामगढ़", state: "Jharkhand", stateHindi: "झारखंड", latitude: 23.6312, longitude: 85.5151 },
  { name: "Medininagar", nameHindi: "मेदिनीनगर", state: "Jharkhand", stateHindi: "झारखंड", latitude: 24.0734, longitude: 84.0780 },

  // Chhattisgarh
  { name: "Raipur", nameHindi: "रायपुर", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 21.2514, longitude: 81.6296 },
  { name: "Bhilai", nameHindi: "भिलाई", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 21.1938, longitude: 81.3509 },
  { name: "Korba", nameHindi: "कोरबा", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 22.3595, longitude: 82.7501 },
  { name: "Bilaspur", nameHindi: "बिलासपुर", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 22.0797, longitude: 82.1391 },
  { name: "Durg", nameHindi: "दुर्ग", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 21.1901, longitude: 81.2849 },
  { name: "Rajnandgaon", nameHindi: "राजनांदगांव", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 21.0974, longitude: 81.0379 },
  { name: "Jagdalpur", nameHindi: "जगदलपुर", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 19.0821, longitude: 82.0323 },
  { name: "Raigarh", nameHindi: "रायगढ़", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 21.8974, longitude: 83.3950 },
  { name: "Ambikapur", nameHindi: "अंबिकापुर", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 23.1204, longitude: 83.1973 },
  { name: "Mahasamund", nameHindi: "महासमुंद", state: "Chhattisgarh", stateHindi: "छत्तीसगढ़", latitude: 21.1074, longitude: 82.0988 },

  // Punjab
  { name: "Ludhiana", nameHindi: "लुधियाना", state: "Punjab", stateHindi: "पंजाब", latitude: 30.9010, longitude: 75.8573 },
  { name: "Amritsar", nameHindi: "अमृतसर", state: "Punjab", stateHindi: "पंजाब", latitude: 31.6340, longitude: 74.8723 },
  { name: "Jalandhar", nameHindi: "जालंधर", state: "Punjab", stateHindi: "पंजाब", latitude: 31.3260, longitude: 75.5762 },
  { name: "Patiala", nameHindi: "पटियाला", state: "Punjab", stateHindi: "पंजाब", latitude: 30.3398, longitude: 76.3869 },
  { name: "Bathinda", nameHindi: "बठिंडा", state: "Punjab", stateHindi: "पंजाब", latitude: 30.2110, longitude: 74.9455 },
  { name: "Hoshiarpur", nameHindi: "होशियारपुर", state: "Punjab", stateHindi: "पंजाब", latitude: 31.5344, longitude: 75.9112 },
  { name: "Batala", nameHindi: "बटाला", state: "Punjab", stateHindi: "पंजाब", latitude: 31.8202, longitude: 75.2049 },
  { name: "Moga", nameHindi: "मोगा", state: "Punjab", stateHindi: "पंजाब", latitude: 30.8176, longitude: 75.1710 },
  { name: "Malerkotla", nameHindi: "मलेरकोटला", state: "Punjab", stateHindi: "पंजाब", latitude: 30.5270, longitude: 75.8792 },
  { name: "Khanna", nameHindi: "खन्ना", state: "Punjab", stateHindi: "पंजाब", latitude: 30.7057, longitude: 76.2194 },
  { name: "Phagwara", nameHindi: "फगवाड़ा", state: "Punjab", stateHindi: "पंजाब", latitude: 31.2244, longitude: 75.7729 },
  { name: "Muktsar", nameHindi: "मुक्तसर", state: "Punjab", stateHindi: "पंजाब", latitude: 30.4762, longitude: 74.5159 },
  { name: "Barnala", nameHindi: "बरनाला", state: "Punjab", stateHindi: "पंजाब", latitude: 30.3781, longitude: 75.5444 },
  { name: "Firozpur", nameHindi: "फिरोजपुर", state: "Punjab", stateHindi: "पंजाब", latitude: 30.9287, longitude: 74.6108 },
  { name: "Pathankot", nameHindi: "पठानकोट", state: "Punjab", stateHindi: "पंजाब", latitude: 32.2746, longitude: 75.652 },
  { name: "Mansa", nameHindi: "मानसा", state: "Punjab", stateHindi: "पंजाब", latitude: 29.9988, longitude: 75.3932 },
  { name: "Mohali", nameHindi: "मोहाली", state: "Punjab", stateHindi: "पंजाब", latitude: 30.7046, longitude: 76.7179 },
  { name: "Zirakpur", nameHindi: "जीरकपुर", state: "Punjab", stateHindi: "पंजाब", latitude: 30.6430, longitude: 76.8217 },
  { name: "Kot Kapura", nameHindi: "कोट कपूरा", state: "Punjab", stateHindi: "पंजाब", latitude: 30.5820, longitude: 74.8130 },
  { name: "Faridkot", nameHindi: "फरीदकोट", state: "Punjab", stateHindi: "पंजाब", latitude: 30.6735, longitude: 74.7455 },

  // Haryana
  { name: "Faridabad", nameHindi: "फरीदाबाद", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.4089, longitude: 77.3178 },
  { name: "Gurgaon", nameHindi: "गुड़गांव", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.4595, longitude: 77.0266 },
  { name: "Panipat", nameHindi: "पानीपत", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.3909, longitude: 76.9635 },
  { name: "Ambala", nameHindi: "अंबाला", state: "Haryana", stateHindi: "हरियाणा", latitude: 30.3753, longitude: 76.7821 },
  { name: "Yamunanagar", nameHindi: "यमुनानगर", state: "Haryana", stateHindi: "हरियाणा", latitude: 30.1290, longitude: 77.2674 },
  { name: "Rohtak", nameHindi: "रोहतक", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.8955, longitude: 76.6066 },
  { name: "Hisar", nameHindi: "हिसार", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.1492, longitude: 75.7217 },
  { name: "Karnal", nameHindi: "करनाल", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.6857, longitude: 76.9905 },
  { name: "Sonipat", nameHindi: "सोनीपत", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.9931, longitude: 77.0151 },
  { name: "Panchkula", nameHindi: "पंचकुला", state: "Haryana", stateHindi: "हरियाणा", latitude: 30.6942, longitude: 76.8606 },
  { name: "Bhiwani", nameHindi: "भिवानी", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.7936, longitude: 76.1272 },
  { name: "Sirsa", nameHindi: "सिरसा", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.5343, longitude: 75.0270 },
  { name: "Jind", nameHindi: "जींद", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.3167, longitude: 76.3150 },
  { name: "Thanesar", nameHindi: "थानेसर", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.9735, longitude: 76.8342 },
  { name: "Kaithal", nameHindi: "कैथल", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.8021, longitude: 76.3869 },
  { name: "Palwal", nameHindi: "पलवल", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.1441, longitude: 77.3270 },
  { name: "Hansi", nameHindi: "हांसी", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.1033, longitude: 75.9647 },
  { name: "Narnaul", nameHindi: "नारनौल", state: "Haryana", stateHindi: "हरियाणा", latitude: 28.0441, longitude: 76.1081 },
  { name: "Fatehabad", nameHindi: "फतेहाबाद", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.5125, longitude: 75.4556 },
  { name: "Gohana", nameHindi: "गोहाना", state: "Haryana", stateHindi: "हरियाणा", latitude: 29.1394, longitude: 76.7066 },

  // Kerala
  { name: "Thiruvananthapuram", nameHindi: "तिरुवनंतपुरम", state: "Kerala", stateHindi: "केरल", latitude: 8.5241, longitude: 76.9366 },
  { name: "Kochi", nameHindi: "कोच्चि", state: "Kerala", stateHindi: "केरल", latitude: 9.9312, longitude: 76.2673 },
  { name: "Kozhikode", nameHindi: "कोझिकोड", state: "Kerala", stateHindi: "केरल", latitude: 11.2588, longitude: 75.7804 },
  { name: "Kollam", nameHindi: "कोल्लम", state: "Kerala", stateHindi: "केरल", latitude: 8.8932, longitude: 76.6141 },
  { name: "Thrissur", nameHindi: "त्रिशूर", state: "Kerala", stateHindi: "केरल", latitude: 10.5276, longitude: 76.2144 },
  { name: "Alappuzha", nameHindi: "अलाप्पुझा", state: "Kerala", stateHindi: "केरल", latitude: 9.4981, longitude: 76.3388 },
  { name: "Kottayam", nameHindi: "कोट्टायम", state: "Kerala", stateHindi: "केरल", latitude: 9.5916, longitude: 76.5222 },
  { name: "Palakkad", nameHindi: "पलक्कड़", state: "Kerala", stateHindi: "केरल", latitude: 10.7867, longitude: 76.6548 },
  { name: "Malappuram", nameHindi: "मलप्पुरम", state: "Kerala", stateHindi: "केरल", latitude: 11.0732, longitude: 76.0831 },
  { name: "Kannur", nameHindi: "कन्नूर", state: "Kerala", stateHindi: "केरल", latitude: 11.8745, longitude: 75.3704 },
  { name: "Kasaragod", nameHindi: "कासरगोड", state: "Kerala", stateHindi: "केरल", latitude: 12.4996, longitude: 74.9869 },
  { name: "Idukki", nameHindi: "इडुक्की", state: "Kerala", stateHindi: "केरल", latitude: 9.8560, longitude: 76.9774 },
  { name: "Wayanad", nameHindi: "वायनाड", state: "Kerala", stateHindi: "केरल", latitude: 11.6054, longitude: 76.0843 },
  { name: "Pathanamthitta", nameHindi: "पठानमतिट्टा", state: "Kerala", stateHindi: "केरल", latitude: 9.2648, longitude: 76.7870 },

  // Assam
  { name: "Guwahati", nameHindi: "गुवाहाटी", state: "Assam", stateHindi: "असम", latitude: 26.1445, longitude: 91.7362 },
  { name: "Silchar", nameHindi: "सिल्चर", state: "Assam", stateHindi: "असम", latitude: 24.8333, longitude: 92.7789 },
  { name: "Dibrugarh", nameHindi: "डिब्रूगढ़", state: "Assam", stateHindi: "असम", latitude: 27.4728, longitude: 94.9120 },
  { name: "Jorhat", nameHindi: "जोरहाट", state: "Assam", stateHindi: "असम", latitude: 26.7509, longitude: 94.2037 },
  { name: "Nagaon", nameHindi: "नगांव", state: "Assam", stateHindi: "असम", latitude: 26.3484, longitude: 92.6855 },
  { name: "Tinsukia", nameHindi: "तिनसुकिया", state: "Assam", stateHindi: "असम", latitude: 27.4900, longitude: 95.3597 },
  { name: "Tezpur", nameHindi: "तेजपुर", state: "Assam", stateHindi: "असम", latitude: 26.6335, longitude: 92.8001 },
  { name: "Bongaigaon", nameHindi: "बोंगाईगांव", state: "Assam", stateHindi: "असम", latitude: 26.4832, longitude: 90.5526 },
  { name: "Dhubri", nameHindi: "धुबरी", state: "Assam", stateHindi: "असम", latitude: 26.0250, longitude: 89.9706 },
  { name: "Diphu", nameHindi: "दीफू", state: "Assam", stateHindi: "असम", latitude: 25.8418, longitude: 93.4307 },
  { name: "North Lakhimpur", nameHindi: "उत्तर लखीमपुर", state: "Assam", stateHindi: "असम", latitude: 27.2333, longitude: 94.1000 },
  { name: "Karimganj", nameHindi: "करीमगंज", state: "Assam", stateHindi: "असम", latitude: 24.8697, longitude: 92.3573 },
  { name: "Sivasagar", nameHindi: "शिवसागर", state: "Assam", stateHindi: "असम", latitude: 26.9708, longitude: 94.6378 },
  { name: "Goalpara", nameHindi: "गोआलपाड़ा", state: "Assam", stateHindi: "असम", latitude: 26.1732, longitude: 90.6194 },

  // Himachal Pradesh
  { name: "Shimla", nameHindi: "शिमला", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 31.1048, longitude: 77.1734 },
  { name: "Dharamshala", nameHindi: "धर्मशाला", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 32.2190, longitude: 76.3234 },
  { name: "Solan", nameHindi: "सोलन", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 30.9045, longitude: 77.0967 },
  { name: "Mandi", nameHindi: "मंडी", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 31.7082, longitude: 76.9319 },
  { name: "Palampur", nameHindi: "पालमपुर", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 32.1056, longitude: 76.5367 },
  { name: "Baddi", nameHindi: "बद्दी", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 30.9578, longitude: 76.7881 },
  { name: "Nahan", nameHindi: "नाहन", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 30.5606, longitude: 77.2969 },
  { name: "Kullu", nameHindi: "कुल्लू", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 31.9578, longitude: 77.1092 },
  { name: "Hamirpur", nameHindi: "हमीरपुर", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 31.6883, longitude: 76.5178 },
  { name: "Una", nameHindi: "ऊना", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 31.4649, longitude: 76.2708 },
  { name: "Bilaspur", nameHindi: "बिलासपुर", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 31.3286, longitude: 76.7564 },
  { name: "Chamba", nameHindi: "चम्बा", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 32.5565, longitude: 76.1318 },
  { name: "Manali", nameHindi: "मनाली", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 32.2396, longitude: 77.1887 },
  { name: "Kasauli", nameHindi: "कसौली", state: "Himachal Pradesh", stateHindi: "हिमाचल प्रदेश", latitude: 30.8977, longitude: 76.9664 },

  // Uttarakhand
  { name: "Dehradun", nameHindi: "देहरादून", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 30.3165, longitude: 78.0322 },
  { name: "Haridwar", nameHindi: "हरिद्वार", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.9457, longitude: 78.1642 },
  { name: "Roorkee", nameHindi: "रुड़की", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.8543, longitude: 77.8880 },
  { name: "Haldwani", nameHindi: "हल्द्वानी", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.2183, longitude: 79.5130 },
  { name: "Rudrapur", nameHindi: "रुद्रपुर", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 28.9855, longitude: 79.4077 },
  { name: "Kashipur", nameHindi: "काशीपुर", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.2155, longitude: 78.9560 },
  { name: "Rishikesh", nameHindi: "ऋषिकेश", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 30.0869, longitude: 78.2676 },
  { name: "Nainital", nameHindi: "नैनीताल", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.3803, longitude: 79.4636 },
  { name: "Almora", nameHindi: "अल्मोड़ा", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.5971, longitude: 79.6593 },
  { name: "Mussoorie", nameHindi: "मसूरी", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 30.4598, longitude: 78.0664 },
  { name: "Tehri", nameHindi: "टिहरी", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 30.3886, longitude: 78.4802 },
  { name: "Pithoragarh", nameHindi: "पिथौरागढ़", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.5825, longitude: 80.2094 },
  { name: "Bageshwar", nameHindi: "बागेश्वर", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.8439, longitude: 79.7697 },
  { name: "Champawat", nameHindi: "चम्पावत", state: "Uttarakhand", stateHindi: "उत्तराखंड", latitude: 29.3367, longitude: 80.0955 },

  // Goa
  { name: "Panaji", nameHindi: "पणजी", state: "Goa", stateHindi: "गोवा", latitude: 15.4909, longitude: 73.8278 },
  { name: "Vasco da Gama", nameHindi: "वास्को डी गामा", state: "Goa", stateHindi: "गोवा", latitude: 15.3954, longitude: 73.8303 },
  { name: "Margao", nameHindi: "मडगांव", state: "Goa", stateHindi: "गोवा", latitude: 15.2832, longitude: 73.9862 },
  { name: "Mapusa", nameHindi: "मापुसा", state: "Goa", stateHindi: "गोवा", latitude: 15.5909, longitude: 73.8161 },
  { name: "Ponda", nameHindi: "पोंडा", state: "Goa", stateHindi: "गोवा", latitude: 15.4013, longitude: 74.0093 },
  { name: "Bicholim", nameHindi: "बिचोलिम", state: "Goa", stateHindi: "गोवा", latitude: 15.5957, longitude: 73.9493 },
  { name: "Curchorem", nameHindi: "कुर्चोरेम", state: "Goa", stateHindi: "गोवा", latitude: 15.2840, longitude: 74.1106 },
  { name: "Sanquelim", nameHindi: "सांकेलिम", state: "Goa", stateHindi: "गोवा", latitude: 15.5827, longitude: 74.0093 },

  // Jammu and Kashmir / Ladakh
  { name: "Srinagar", nameHindi: "श्रीनगर", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 34.0837, longitude: 74.7973 },
  { name: "Jammu", nameHindi: "जम्मू", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 32.7266, longitude: 74.8570 },
  { name: "Anantnag", nameHindi: "अनंतनाग", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 33.7311, longitude: 75.1464 },
  { name: "Baramulla", nameHindi: "बारामूला", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 34.2097, longitude: 74.3436 },
  { name: "Sopore", nameHindi: "सोपोर", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 34.3030, longitude: 74.4661 },
  { name: "Kathua", nameHindi: "कठुआ", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 32.3700, longitude: 75.5183 },
  { name: "Udhampur", nameHindi: "उधमपुर", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 32.9155, longitude: 75.1416 },
  { name: "Punch", nameHindi: "पुंछ", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 33.7700, longitude: 74.0960 },
  { name: "Rajouri", nameHindi: "राजौरी", state: "Jammu and Kashmir", stateHindi: "जम्मू और कश्मीर", latitude: 33.3833, longitude: 74.3117 },
  { name: "Leh", nameHindi: "लेह", state: "Ladakh", stateHindi: "लद्दाख", latitude: 34.1526, longitude: 77.5770 },
  { name: "Kargil", nameHindi: "कारगिल", state: "Ladakh", stateHindi: "लद्दाख", latitude: 34.5539, longitude: 76.1313 },

  // Manipur
  { name: "Imphal", nameHindi: "इम्फाल", state: "Manipur", stateHindi: "मणिपुर", latitude: 24.8170, longitude: 93.9368 },
  { name: "Thoubal", nameHindi: "थौबल", state: "Manipur", stateHindi: "मणिपुर", latitude: 24.6377, longitude: 93.9899 },
  { name: "Bishnupur", nameHindi: "बिष्णुपुर", state: "Manipur", stateHindi: "मणिपुर", latitude: 24.6467, longitude: 93.7717 },
  { name: "Churachandpur", nameHindi: "चुराचांदपुर", state: "Manipur", stateHindi: "मणिपुर", latitude: 24.3333, longitude: 93.6833 },

  // Meghalaya
  { name: "Shillong", nameHindi: "शिलांग", state: "Meghalaya", stateHindi: "मेघालय", latitude: 25.5788, longitude: 91.8933 },
  { name: "Tura", nameHindi: "तुरा", state: "Meghalaya", stateHindi: "मेघालय", latitude: 25.5138, longitude: 90.2035 },
  { name: "Jowai", nameHindi: "जोवाई", state: "Meghalaya", stateHindi: "मेघालय", latitude: 25.4500, longitude: 92.1958 },
  { name: "Nongpoh", nameHindi: "नोंगपोह", state: "Meghalaya", stateHindi: "मेघालय", latitude: 25.8492, longitude: 91.8831 },

  // Tripura  
  { name: "Agartala", nameHindi: "अगरतला", state: "Tripura", stateHindi: "त्रिपुरा", latitude: 23.8315, longitude: 91.2868 },
  { name: "Dharmanagar", nameHindi: "धर्मनगर", state: "Tripura", stateHindi: "त्रिपुरा", latitude: 24.3731, longitude: 92.1693 },
  { name: "Udaipur", nameHindi: "उदयपुर", state: "Tripura", stateHindi: "त्रिपुरा", latitude: 23.5333, longitude: 91.4833 },
  { name: "Kailashahar", nameHindi: "कैलाशहर", state: "Tripura", stateHindi: "त्रिपुरा", latitude: 24.3347, longitude: 92.0042 },

  // Mizoram
  { name: "Aizawl", nameHindi: "आइजोल", state: "Mizoram", stateHindi: "मिजोरम", latitude: 23.7271, longitude: 92.7176 },
  { name: "Lunglei", nameHindi: "लुंगलेई", state: "Mizoram", stateHindi: "मिजोरम", latitude: 22.8880, longitude: 92.7342 },
  { name: "Saiha", nameHindi: "साइहा", state: "Mizoram", stateHindi: "मिजोरम", latitude: 22.4850, longitude: 92.9742 },
  { name: "Champhai", nameHindi: "चम्फाई", state: "Mizoram", stateHindi: "मिजोरम", latitude: 23.4605, longitude: 93.3260 },

  // Nagaland
  { name: "Kohima", nameHindi: "कोहिमा", state: "Nagaland", stateHindi: "नगालैंड", latitude: 25.6751, longitude: 94.1086 },
  { name: "Dimapur", nameHindi: "दीमापुर", state: "Nagaland", stateHindi: "नगालैंड", latitude: 25.9044, longitude: 93.7267 },
  { name: "Mokokchung", nameHindi: "मोकोकचुंग", state: "Nagaland", stateHindi: "नगालैंड", latitude: 26.3229, longitude: 94.5267 },
  { name: "Tuensang", nameHindi: "तुएनसांग", state: "Nagaland", stateHindi: "नगालैंड", latitude: 26.2833, longitude: 94.8333 },

  // Arunachal Pradesh
  { name: "Itanagar", nameHindi: "ईटानगर", state: "Arunachal Pradesh", stateHindi: "अरुणाचल प्रदेश", latitude: 27.0844, longitude: 93.6053 },
  { name: "Naharlagun", nameHindi: "नाहरलगुन", state: "Arunachal Pradesh", stateHindi: "अरुणाचल प्रदेश", latitude: 27.1005, longitude: 93.7001 },
  { name: "Pasighat", nameHindi: "पासीघाट", state: "Arunachal Pradesh", stateHindi: "अरुणाचल प्रदेश", latitude: 28.0669, longitude: 95.3267 },
  { name: "Tezpur", nameHindi: "तेजपुर", state: "Arunachal Pradesh", stateHindi: "अरुणाचल प्रदेश", latitude: 26.6335, longitude: 92.8001 },

  // Sikkim
  { name: "Gangtok", nameHindi: "गंगटोक", state: "Sikkim", stateHindi: "सिक्किम", latitude: 27.3389, longitude: 88.6065 },
  { name: "Namchi", nameHindi: "नामची", state: "Sikkim", stateHindi: "सिक्किम", latitude: 27.1667, longitude: 88.3667 },
  { name: "Geyzing", nameHindi: "गेज़िंग", state: "Sikkim", stateHindi: "सिक्किम", latitude: 27.4833, longitude: 88.2667 },
  { name: "Mangan", nameHindi: "मंगन", state: "Sikkim", stateHindi: "सिक्किम", latitude: 27.5167, longitude: 88.5333 }
];

export function searchCities(query: string): City[] {
  if (!query.trim()) return indianCities.slice(0, 8);
  
  const searchTerm = query.toLowerCase();
  return indianCities.filter(city => 
    city.name.toLowerCase().includes(searchTerm) ||
    city.nameHindi.includes(query) ||
    city.state.toLowerCase().includes(searchTerm) ||
    city.stateHindi.includes(query)
  ).slice(0, 8);
}
